stages:
    - build
    - test

test-job:
    stage: test
    script:
        - echo "git-lab ci TEST JOB running"

build-job:
    stage: build
    script:
        - echo "git-lab ci TEST JOB running"
