variables:
    TEST_GLOBAL_VARIABLE: "Hello"

stages:
    - build
    - test

test-job1:
    stage: test
    script:
        - echo "$TEST_GLOBAL_VARIABLE"

test-job2:
    stage: build
    script:
        - echo "test 2"

build-job:
    stage: build
    script:
        - echo "git-lab ci TEST JOB running"
