variables:
    TEST_GLOBAL_VARIABLE: "Hello"

stages:
    - build
    - test

test-job:
    stage: test
    script:
        - echo "git-lab ci TEST JOB running"
        - echo "$TEST_GLOBAL_VARIABLE World!"

build-job:
    stage: build
    script:
        - echo "git-lab ci TEST JOB running"
