services:
  server:
    container_name: library_server
    build: 
      context: .
    ports:
      - 127.0.0.1:5000:80
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Connection__MongoConnection=mongodb://root:root@mongo/
      - Connection__RedisConnection=redis:6379
      - Redis__IsUseRedis=true
  
  mongo:
    container_name: mongo
    image: mongo
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - default

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default
    environment:
      - REDIS_PORT=6379
    volumes:
      - redis_data:/data

networks:
  default:
    driver: bridge

volumes:
  mongo_data:
  redis_data: