services:
  server:
    container_name: library_server
    build: 
      context: .
    ports:
      - 127.0.0.1:5000:80
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Connection__MongoConnection=mongodb+srv://root:root@library.ndny8eh.mongodb.net/
      - Connection__RedisConnection=redis,6379;Password=root
# docker run --name redis_library -v redis_data:/data -c --port 6380 redis
# docker run -d --name redis-stack-server -p 127.0.0.1:6379:6379 redis/redis-stack-server:latest

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass root
    networks:
      - default



networks:
  default:
    driver: bridge

volumes:
  mongo_data:
  redis_data: