services:
  server:
    container_name: library_server
    build: 
      context: .
    ports:
      - 127.0.0.1:5000:80
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Connection__MongoConnection=mongodb+srv://root:root@library.ndny8eh.mongodb.net/
    

networks:
  default:
    driver: bridge

volumes:
  mongo_data: