services:
  server:
    container_name: library_server
    build: 
      context: .
    ports:
      - 127.0.0.1:5000:80
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Connection__MongoConnection=mongodb+srv://root:root@library.ndny8eh.mongodb.net/
      - Connection__RedisConnection=redis:6379
      - CORS__AllowedHosts__0=client:3000
    volumes:
      - static_data:/app/wwwroot

  client:
    container_name: library_client
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - 127.0.0.1:3000:80
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ApiAddress=http://server:80


  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - default
    environment:
      - REDIS_PORT=6379
    volumes:
      - redis_data:/data



networks:
  default:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
  static_data: